---

pool:
  name: Default

trigger:
  - main

steps:
  - task: Docker@2
    displayName: 'Build docker image and push to repository'
    inputs:
      command: buildAndPush
      Dockerfile: 'Dockerfile'
      containerRegistry: 'MyDockerHub'
      repository: 'vasavimadishetty/sample_vasavi_2024'
      tags: '$(Build.BuildId)'